package com.thekirankumarv.newsync.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF0700CE)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF373DFF)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF7E3BBE)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC080FF)
val onSecondaryContainerLight = Color(0xFF1C0036)
val tertiaryLight = Color(0xFF7E00BA)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAB3AEB)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1A1B25)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1A1B25)
val surfaceVariantLight = Color(0xFFE2E0F7)
val onSurfaceVariantLight = Color(0xFF454557)
val outlineLight = Color(0xFF767589)
val outlineVariantLight = Color(0xFFC6C4DA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F2F3B)
val inverseOnSurfaceLight = Color(0xFFF1EFFE)
val inversePrimaryLight = Color(0xFFBFC2FF)
val surfaceDimLight = Color(0xFFDAD8E7)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F2FF)
val surfaceContainerLight = Color(0xFFEEECFB)
val surfaceContainerHighLight = Color(0xFFE9E6F6)
val surfaceContainerHighestLight = Color(0xFFE3E1F0)

val primaryDark = Color(0xFFBFC2FF)
val onPrimaryDark = Color(0xFF0400AC)
val primaryContainerDark = Color(0xFF0D05EC)
val onPrimaryContainerDark = Color(0xFFDEDDFF)
val secondaryDark = Color(0xFFDDB8FF)
val onSecondaryDark = Color(0xFF490080)
val secondaryContainerDark = Color(0xFF9653D7)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFFE6B4FF)
val onTertiaryDark = Color(0xFF4F0076)
val tertiaryContainerDark = Color(0xFFAB3AEB)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12131D)
val onBackgroundDark = Color(0xFFE3E1F0)
val surfaceDark = Color(0xFF12131D)
val onSurfaceDark = Color(0xFFE3E1F0)
val surfaceVariantDark = Color(0xFF454557)
val onSurfaceVariantDark = Color(0xFFC6C4DA)
val outlineDark = Color(0xFF8F8FA3)
val outlineVariantDark = Color(0xFF454557)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E1F0)
val inverseOnSurfaceDark = Color(0xFF2F2F3B)
val inversePrimaryDark = Color(0xFF363CFF)
val surfaceDimDark = Color(0xFF12131D)
val surfaceBrightDark = Color(0xFF383844)
val surfaceContainerLowestDark = Color(0xFF0D0D17)
val surfaceContainerLowDark = Color(0xFF1A1B25)
val surfaceContainerDark = Color(0xFF1E1F29)
val surfaceContainerHighDark = Color(0xFF292934)
val surfaceContainerHighestDark = Color(0xFF34343F)








